project:
  type: book

book:
  title: "Hurtownie danych i analityczne metody przetwarzania"
  author: "Łukasz Wawrowski"
  date: ""
  chapters:
    - index.qmd
    - 00-organizacja.qmd
    - 01-eda.qmd
    - 02-data-cleaning.qmd
    - 03-azure-data-lake.qmd
    - 04-azure-sql.qmd
    - 05-mlflow.qmd
    - 06-prefect.qmd
    - 07-dvc.qmd
    
format:
  html:
    toc-title: "Spis treści"
    theme:
      - cosmo
      - brand
